
<div class="row">
    <div class="col-md-12 col-sm-12">

        <div class="panel panel-default">

            <div class="panel-header">
                <h4 class="panel-title">
                    <?php echo $this->entity; ?>
                </h4>
            </div> <!-- /.panel-header -->

            <div class="panel-body">    
                  <?php echo $this->RenderCdiGrid($this->grid); ?>


            </div> <!-- /.panel-body -->

        </div> <!-- /.panel -->

    </div>
</div>
