
<div class="cview">
    <div class="row">

        <!-- /.col-lg-6 -->
        <div class="col-lg-12">
            <div class="panel panel-danger">
                <div class="panel-heading">
                  <?php echo $this->rentity->getName(); ?>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#info" data-toggle="tab">info</a>
                        </li>

                        <?php foreach ($this->rentity->getProperties() as $property): ?>
                            <?php if ($property->getType() == "oneToMany"): ?>
                                <li ><a href="#<?php echo $property->getName(); ?>" data-toggle="tab"><?php echo $property->getName(); ?></a>
                                </li>

                            <?php endif; ?>


                        <?php endforeach; ?>


                    </ul>

                    <!-- Tab panes -->
                    <div class="tab-content">
                        
                         <div class="tab-pane fade in active" id="info">
                                    <?php echo $this->partial("cdi-entity/partial/form-entity", array("entity" => $this->object)); ?>

                                </div>
                        
                        <?php foreach ($this->rentity->getProperties() as $property): ?>

                            <?php if ($property->getType() == "oneToMany"): ?>
                                <div class="tab-pane fade" id="<?php echo $property->getName(); ?>">
                                  
                                        <?php echo $this->partial("cdi-entity/partial/onetomany", array("oid" => $this->object->getId(),"parentEntity" => $this->rentity,"subEntity" => $property)); ?>

                                </div>
                            <?php endif; ?>
                        <?php endforeach; ?>


                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-6 -->
    </div>
</div>
