<div class="cview">
    <div class="row">

        <!-- /.col-lg-6 -->
        <div class="col-lg-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h4 class="panel-title"><?php echo $this->entity->getName(); ?> </h4> 
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#info" data-toggle="tab"><?php echo $this->entity->getName(); ?></a>
                        </li>

                        <?php foreach ($this->entity->getProperties() as $property): ?>
                            <?php if ($property->getType() == "oneToMany"): ?>
                                <li ><a href="#<?php echo $property->getName(); ?>" data-toggle="tab"><?php echo ucfirst($property->getName()); ?></a>
                                </li>

                            <?php endif; ?>


                        <?php endforeach; ?>


                    </ul>

                    <!-- Tab panes -->
                    <div class="tab-content">

                        <div class="tab-pane fade in active" id="info">
                            <?php echo $this->CdiEntityRenderForm($this->editor->getCrudForm(), "two", "top"); ?>

                        </div>

                        <?php foreach ($this->entity->getProperties() as $property): ?>

                            <?php if ($property->getType() == "oneToMany"): ?>
                                <div class="tab-pane fade" id="<?php echo $property->getName(); ?>">
                                    <?php if ($this->oid): ?>
                                 
                                        <?php echo $this->partial("cdi-entity/partial/editor/onetomany", array("oid" => $this->oid, "parentEntity" => $this->entity, "subEntity" => $property->getRelatedEntity())); ?>


                                    <?php endif; ?>

                                </div>
                            <?php endif; ?>
                        <?php endforeach; ?>


                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-6 -->
    </div>
</div>

