
<div class="row">
    <div class="col-md-12 col-sm-12">

        <div class="panel panel-default">

            <div class="panel-header">
                <h4 class="panel-title" name="E" id="E">
                    <?php echo $this->entity; ?>
                </h4>
            </div> <!-- /.panel-header -->

            <div class="panel-body">

                <?php if ($this->result !== null): ?>

                    <?php if ($this->result): ?>
                        <div class="alert alert-success">Se actualizo el esquema</div>

                    <?php else: ?>
                        <div class="alert alert-danger">Error al actualizar el esquema. Por favor contacte a soporte. Error:<?php echo $this->exec; ?></div>
                    <?php endif; ?>

                <?php else: ?>
                    <div class="alert alert-warning">Sin actualizacion de esquema</div>
                <?php endif; ?>

                <?php if ($this->buttonPersistEnable): ?>
                    <div>
                        <a class="btn btn-danger" href="/cdientity/entity/update/<?php echo $this->entity->getId(); ?>">Persist Change on Entity</a>

                    </div>

                <?php endif; ?>


                <?php echo $this->RenderCdiGrid($this->grid); ?>


            </div> <!-- /.panel-body -->

        </div> <!-- /.panel -->

    </div>
</div>

<script>

    $(function () {

        changetype();

    });

    function changetype() {
        var types = $("[name='type'").val();

        if (types == "file") {
            $("#row_absolutepath").show();
            $("#row_webpath").show();
        } else {
            $("#row_absolutepath").hide();
            $("#row_webpath").hide();
        }

        if (types == "oneToOne" || types == "manyToOne" || types == "oneToMany") {
            $("#row_length").hide();
            $("#row_relatedEntity").show();
        } else {

            $("#row_length").show();
            $("#row_relatedEntity").hide();
        }
    }

</script>
