<br>
<div class="clearfix"></div>
<div>
    <h4 class="center" name="E" id="E">
        <?php echo $this->entity; ?>
    </h4>
</div>



<?php if ($this->result !== null): ?>

    <?php if ($this->result): ?>
        <div class="alert alert-success">Se actualizo el esquema</div>

    <?php else: ?>
        <div class="alert alert-danger">Error al actualizar el esquema. Por favor contacte a soporte. Error:<?php echo $this->exec; ?></div>
    <?php endif; ?>

<?php else: ?>
    <div class="alert alert-warning">Sin actualizacion de esquema</div>
<?php endif; ?>

<?php if ($this->buttonPersistEnable): ?>
    <div>
        <a class="btn btn-danger" href="/cdientity/entity/update/<?php echo $this->entity->getId(); ?>">Persist Change on Entity</a>

    </div>

<?php endif; ?>


<?php echo $this->CdiGrid($this->grid); ?>


<script>

    jQuery(function () {

        changetype();

    });


    function changetype() {
        var types = jQuery("[name='type'").val();

        if (types == "file") {
            jQuery("#row_absolutepath").show();
            jQuery("#row_webpath").show();
        } else {
            jQuery("#row_absolutepath").hide();
            jQuery("#row_webpath").hide();
        }

        if (types == "oneToOne" || types == "manyToOne" || types == "oneToMany") {
            jQuery("#row_length").hide();
            jQuery("#row_relatedEntity").show();
        } else {

            jQuery("#row_length").show();
            jQuery("#row_relatedEntity").hide();
        }

    }

</script>
