<div class="row">
    <div class="col-12">
        
   
    <div class="panel panel panel-primary">
        <div class="panel-heading">
            <h4 class="panel-title">Menu Manager</h4>     
        </div>
        <div class="panel-body">
             <div class="col-3 col-lg-3">
                            <div>
                                <a class="btn btn-danger" href="/cdientity/menu/update">Update Menus</a>
                            </div>
                        </div>
            <div class="clearfix padding5"></div>
            <?php echo $this->CdiGrid($this->grid); ?>

        </div>
    </div>
</div>
 </div>

