
<div class="row">
    <div class="col-md-12 col-sm-12">

        <div class="panel panel-default">

            <div class="panel-header">
                <h4 class="panel-title">
                    Entity Manager
                </h4>
            </div> <!-- /.portlet-header -->

            <div class="panel-body">    
        

                <?php echo $this->CdiGrid($this->grid); ?>


            </div> <!-- /.portlet-body -->

        </div> <!-- /.portlet -->

    </div>
</div>
